# Generated by Django 3.2.9 on 2022-01-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditsTaken', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='AdvisingSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=8, null=True)),
                ('semester', models.CharField(blank=True, max_length=6, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('advisingStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.advisingstudent')),
                ('courseTaken', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.section')),
                ('timeSlot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.timeslot')),
            ],
            options={
                'unique_together': {('course', 'semester', 'year', 'advisingStudent', 'section', 'timeSlot')},
            },
        ),
    ]
