# Generated by Django 3.2.9 on 2021-12-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211221_2114'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisingstudent',
            name='advisingDay',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='advisingstudent',
            name='endHour',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='advisingstudent',
            name='endMinute',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='advisingstudent',
            name='prereq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='advisingstudent',
            name='startHour',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='advisingstudent',
            name='startMinute',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
