# Generated by Django 3.2.9 on 2021-12-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211230_1319'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisingslip',
            name='courseTaken',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.course'),
        ),
        migrations.AddField(
            model_name='advisingslip',
            name='semester',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='advisingslip',
            name='year',
            field=models.DecimalField(decimal_places=0, default=456, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='advisingslip',
            unique_together={('courseTaken', 'semester', 'year')},
        ),
    ]
