# Generated by Django 3.2.9 on 2022-01-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisingstudent',
            name='mondayClass',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='advisingstudent',
            name='sundayClass',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='advisingstudent',
            name='thursdayClass',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='advisingstudent',
            name='tuesdayClass',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='advisingstudent',
            name='wednesdayClass',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=1, null=True),
        ),
    ]
