# Generated by Django 3.2.9 on 2021-12-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20211230_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisingslip',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
