# Generated by Django 3.2.9 on 2021-12-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_advisingslip_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advisingslip',
            unique_together={('semester', 'year')},
        ),
        migrations.RemoveField(
            model_name='advisingslip',
            name='courseTaken',
        ),
    ]
