# Generated by Django 3.2.9 on 2021-12-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211222_1407'),
        ('portal', '0003_rename_prereq_advisingstudent_completedcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisingSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.section')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.advisingstudent')),
            ],
        ),
    ]
