# Generated by Django 3.2.9 on 2021-12-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_advisingslip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisingSlip',
        ),
    ]
