# Generated by Django 3.2.9 on 2021-12-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211230_1536'),
        ('portal', '0004_auto_20211230_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisingslip',
            name='course',
            field=models.CharField(default=223, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advisingslip',
            name='courseTaken',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.course'),
        ),
    ]
