# Generated by Django 3.2.9 on 2021-12-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211222_1920'),
        ('portal', '0005_delete_advisingslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisingSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.section')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.advisingstudent')),
            ],
        ),
    ]
