# Generated by Django 3.2.9 on 2021-12-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20211230_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisingslip',
            name='course',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='advisingslip',
            unique_together={('course', 'semester', 'year')},
        ),
    ]
