# Generated by Django 3.2.9 on 2021-12-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20211230_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisingstudent',
            name='creditsTaken',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
    ]
