# Generated by Django 3.2.9 on 2021-12-31 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211231_1814'),
        ('portal', '0007_alter_advisingstudent_creditstaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisingslip',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.section'),
        ),
    ]
