# Generated by Django 3.2.9 on 2021-12-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211231_1816'),
        ('portal', '0008_alter_advisingslip_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advisingslip',
            unique_together={('course', 'semester', 'year', 'advisingStudent', 'section')},
        ),
    ]
