# Generated by Django 3.2.9 on 2021-12-31 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211231_2123'),
        ('portal', '0009_alter_advisingslip_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisingslip',
            name='timeSlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.timeslot'),
        ),
    ]
