# Generated by Django 3.2.9 on 2021-12-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211231_2126'),
        ('portal', '0010_advisingslip_timeslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advisingslip',
            unique_together={('course', 'semester', 'year', 'advisingStudent', 'section', 'timeSlot')},
        ),
    ]
