# Generated by Django 3.2.9 on 2021-12-31 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211231_2137'),
        ('portal', '0011_alter_advisingslip_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisingstudent',
            name='semester',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='advisingstudent',
            name='timeSlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.timeslot'),
        ),
        migrations.AddField(
            model_name='advisingstudent',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='advisingstudent',
            unique_together={('semester', 'year', 'timeSlot')},
        ),
    ]
