# Generated by Django 3.2.9 on 2021-12-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20211231_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advisingstudent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='advisingstudent',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='advisingstudent',
            name='timeSlot',
        ),
        migrations.RemoveField(
            model_name='advisingstudent',
            name='year',
        ),
    ]
