# Generated by Django 3.2.9 on 2021-12-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='img',
            field=models.ImageField(default='DefaultProfilePic.jpg', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('O+', 'O+'), ('B+', 'B+'), ('O-', 'O-'), ('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('O+', 'O+'), ('B+', 'B+'), ('O-', 'O-'), ('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, null=True),
        ),
    ]
