# Generated by Django 3.2.9 on 2021-12-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('A-', 'A-'), ('B+', 'B+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('A-', 'A-'), ('B+', 'B+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('A-', 'A-'), ('C+', 'C+'), ('C-', 'C-'), ('A+', 'A+'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('B+', 'B+'), ('D+', 'D+'), ('C', 'C'), ('B-', 'B-')], max_length=2, null=True),
        ),
    ]
