# Generated by Django 3.2.9 on 2021-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O-', 'O-'), ('AB+', 'AB+'), ('A-', 'A-'), ('O+', 'O+'), ('AB-', 'AB-'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O-', 'O-'), ('AB+', 'AB+'), ('A-', 'A-'), ('O+', 'O+'), ('AB-', 'AB-'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('F', 'F'), ('A', 'A'), ('D', 'D'), ('A-', 'A-'), ('C+', 'C+'), ('B-', 'B-'), ('A+', 'A+'), ('C-', 'C-'), ('D+', 'D+'), ('C', 'C'), ('B', 'B')], max_length=2, null=True),
        ),
    ]
