# Generated by Django 3.2.9 on 2021-12-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('A-', 'A-'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('AB-', 'AB-'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Spring', 'Spring'), ('Fall', 'Fall')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('A-', 'A-'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('AB-', 'AB-'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('C+', 'C+'), ('C-', 'C-'), ('D+', 'D+'), ('A+', 'A+'), ('A', 'A'), ('C', 'C'), ('A-', 'A-'), ('F', 'F'), ('B', 'B'), ('B+', 'B+'), ('B-', 'B-')], max_length=2, null=True),
        ),
    ]
