# Generated by Django 3.2.9 on 2022-01-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('O-', 'O-'), ('AB-', 'AB-'), ('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('O-', 'O-'), ('AB-', 'AB-'), ('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('F', 'F'), ('C', 'C'), ('C+', 'C+'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('B-', 'B-'), ('D+', 'D+'), ('B+', 'B+'), ('A-', 'A-'), ('C-', 'C-')], max_length=2, null=True),
        ),
    ]
