# Generated by Django 3.2.9 on 2021-11-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('classroom', 'semester', 'year', 'time_slot'), ('semester', 'year', 'time_slot', 'course'), ('course', 'sec_id', 'semester', 'year', 'time_slot')},
        ),
    ]
