# Generated by Django 3.2.9 on 2021-12-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('AB+', 'AB+'), ('O+', 'O+'), ('O-', 'O-'), ('AB-', 'AB-'), ('B+', 'B+'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('AB+', 'AB+'), ('O+', 'O+'), ('O-', 'O-'), ('AB-', 'AB-'), ('B+', 'B+'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('C+', 'C+'), ('F', 'F'), ('A', 'A'), ('D', 'D'), ('B-', 'B-'), ('A+', 'A+'), ('C-', 'C-'), ('A-', 'A-'), ('D+', 'D+'), ('B+', 'B+')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_id', 'title')},
        ),
    ]
