# Generated by Django 3.2.9 on 2021-11-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='takes',
            name='course',
            field=models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_course', to='accounts.section'),
        ),
        migrations.AlterField(
            model_name='takes',
            name='sec',
            field=models.ForeignKey(db_column='sec_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_sec', to='accounts.section'),
        ),
        migrations.AlterField(
            model_name='takes',
            name='semester',
            field=models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_semester', to='accounts.section'),
        ),
        migrations.AlterField(
            model_name='takes',
            name='year',
            field=models.ForeignKey(db_column='year', on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_year', to='accounts.section'),
        ),
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together={('course', 'semester', 'year')},
        ),
        migrations.AlterModelTable(
            name='takes',
            table='section',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='section',
        ),
    ]
