# Generated by Django 3.2.9 on 2022-01-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220101_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A-', 'A-'), ('B-', 'B-'), ('D+', 'D+'), ('D', 'D'), ('A', 'A'), ('B+', 'B+'), ('C-', 'C-'), ('C+', 'C+'), ('B', 'B'), ('A+', 'A+'), ('F', 'F')], max_length=2, null=True),
        ),
    ]
