# Generated by Django 3.2.9 on 2021-12-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211221_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('O+', 'O+'), ('AB-', 'AB-'), ('B+', 'B+'), ('O-', 'O-'), ('AB+', 'AB+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('O+', 'O+'), ('AB-', 'AB-'), ('B+', 'B+'), ('O-', 'O-'), ('AB+', 'AB+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C+', 'C+'), ('B', 'B'), ('D+', 'D+'), ('B-', 'B-'), ('F', 'F'), ('D', 'D'), ('A+', 'A+'), ('C', 'C'), ('C-', 'C-'), ('A', 'A'), ('B+', 'B+'), ('A-', 'A-')], max_length=2, null=True),
        ),
    ]
