# Generated by Django 3.2.9 on 2021-11-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211128_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('semester', 'year', 'time_slot', 'course'), ('course', 'sec_id', 'semester', 'year', 'time_slot'), ('sec_id', 'course', 'semester', 'year'), ('semester', 'year', 'time_slot', 'instructor'), ('classroom', 'semester', 'year', 'time_slot')},
        ),
    ]
