# Generated by Django 3.2.9 on 2021-12-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211225_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('O-', 'O-'), ('B+', 'B+'), ('O+', 'O+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('O-', 'O-'), ('B+', 'B+'), ('O+', 'O+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('D', 'D'), ('A+', 'A+'), ('D+', 'D+'), ('A', 'A'), ('C', 'C'), ('A-', 'A-'), ('C-', 'C-'), ('C+', 'C+'), ('F', 'F'), ('B-', 'B-'), ('B+', 'B+')], max_length=2, null=True),
        ),
    ]
