# Generated by Django 3.2.9 on 2021-12-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211227_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('O+', 'O+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('O+', 'O+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('F', 'F'), ('A+', 'A+'), ('D', 'D'), ('D+', 'D+'), ('C+', 'C+'), ('C-', 'C-'), ('B+', 'B+'), ('B-', 'B-'), ('B', 'B'), ('A-', 'A-'), ('C', 'C')], max_length=2, null=True),
        ),
    ]
