# Generated by Django 3.2.9 on 2021-12-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211202_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O+', 'O+'), ('A+', 'A+'), ('O-', 'O-'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O+', 'O+'), ('A+', 'A+'), ('O-', 'O-'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C', 2.0), ('B', 3.0), ('D+', 1.3), ('C+', 2.3), ('B+', 3.3), ('B-', 2.7), ('A', 4.0), ('F', 0.0), ('A-', 3.7), ('C-', 1.7), ('D', 1.0), ('A+', 4.0)], max_length=2, null=True),
        ),
    ]
