# Generated by Django 3.2.9 on 2022-01-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220102_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB-', 'AB-'), ('O-', 'O-'), ('A-', 'A-'), ('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB-', 'AB-'), ('O-', 'O-'), ('A-', 'A-'), ('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('A', 'A'), ('D+', 'D+'), ('C-', 'C-'), ('B', 'B'), ('C', 'C'), ('B+', 'B+'), ('C+', 'C+'), ('D', 'D'), ('F', 'F')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
    ]
