# Generated by Django 3.2.9 on 2021-12-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211227_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('O-', 'O-'), ('B+', 'B+'), ('AB-', 'AB-'), ('A+', 'A+'), ('AB+', 'AB+'), ('O+', 'O+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('O-', 'O-'), ('B+', 'B+'), ('AB-', 'AB-'), ('A+', 'A+'), ('AB+', 'AB+'), ('O+', 'O+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('A-', 'A-'), ('B-', 'B-'), ('D+', 'D+'), ('F', 'F'), ('C+', 'C+'), ('C-', 'C-'), ('B', 'B'), ('B+', 'B+'), ('C', 'C'), ('A+', 'A+'), ('A', 'A')], max_length=2, null=True),
        ),
    ]
