# Generated by Django 3.2.9 on 2021-11-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211124_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='time_slot_id',
        ),
        migrations.AddField(
            model_name='section',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.timeslot'),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
    ]
