# Generated by Django 3.2.9 on 2021-12-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211221_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('A+', 'A+'), ('A-', 'A-'), ('O-', 'O-'), ('O+', 'O+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('A+', 'A+'), ('A-', 'A-'), ('O-', 'O-'), ('O+', 'O+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('D+', 'D+'), ('B-', 'B-'), ('C+', 'C+'), ('A', 'A'), ('A-', 'A-'), ('F', 'F'), ('B+', 'B+'), ('D', 'D'), ('B', 'B'), ('A+', 'A+'), ('C', 'C'), ('C-', 'C-')], max_length=2, null=True),
        ),
    ]
