# Generated by Django 3.2.9 on 2021-11-29 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211129_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='section',
            field=models.OneToOneField(default=1234, on_delete=django.db.models.deletion.CASCADE, to='accounts.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='takes',
            table=None,
        ),
        migrations.RemoveField(
            model_name='takes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='sec',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='year',
        ),
    ]
