# Generated by Django 3.2.9 on 2021-12-24 07:25

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211224_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completedCourses',
            field=django_mysql.models.ListCharField(models.CharField(max_length=8), default=456, max_length=90, size=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('A-', 'A-'), ('AB-', 'AB-'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('A-', 'A-'), ('AB-', 'AB-'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C-', 'C-'), ('A-', 'A-'), ('D', 'D'), ('B-', 'B-'), ('D+', 'D+'), ('B+', 'B+'), ('A+', 'A+'), ('C', 'C'), ('B', 'B'), ('F', 'F'), ('C+', 'C+'), ('A', 'A')], max_length=2, null=True),
        ),
    ]
