# Generated by Django 3.2.9 on 2021-11-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211119_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentId',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
