# Generated by Django 3.2.9 on 2021-12-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211230_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('AB-', 'AB-'), ('O+', 'O+'), ('AB+', 'AB+'), ('O-', 'O-'), ('A-', 'A-'), ('B+', 'B+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('AB-', 'AB-'), ('O+', 'O+'), ('AB+', 'AB+'), ('O-', 'O-'), ('A-', 'A-'), ('B+', 'B+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C-', 'C-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('F', 'F'), ('C+', 'C+'), ('D+', 'D+'), ('C', 'C'), ('B', 'B'), ('A-', 'A-'), ('D', 'D'), ('A', 'A')], max_length=2, null=True),
        ),
    ]
