# Generated by Django 3.2.9 on 2022-01-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220105_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('D+', 'D+'), ('F', 'F'), ('A-', 'A-'), ('B-', 'B-'), ('B+', 'B+'), ('A', 'A'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('A+', 'A+'), ('B', 'B'), ('C+', 'C+')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.instructor')),
                ('s', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
