# Generated by Django 3.2.9 on 2021-12-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211221_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('A+', 'A+'), ('O+', 'O+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('B+', 'B+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('A+', 'A+'), ('O+', 'O+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('B+', 'B+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('A+', 'A+'), ('C+', 'C+'), ('D', 'D'), ('B', 'B'), ('C', 'C'), ('F', 'F'), ('B-', 'B-'), ('A', 'A'), ('D+', 'D+'), ('C-', 'C-'), ('B+', 'B+')], max_length=2, null=True),
        ),
    ]
