# Generated by Django 3.2.9 on 2021-12-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211204_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('AB+', 'AB+'), ('B+', 'B+'), ('A-', 'A-'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Spring', 'Spring'), ('Fall', 'Fall')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('AB+', 'AB+'), ('B+', 'B+'), ('A-', 'A-'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('B', 'B'), ('A-', 'A-'), ('F', 'F'), ('D+', 'D+'), ('C-', 'C-'), ('C+', 'C+'), ('A+', 'A+'), ('C', 'C'), ('B+', 'B+'), ('A', 'A'), ('B-', 'B-')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together={('takes_id', 'section')},
        ),
    ]
