# Generated by Django 3.2.9 on 2021-12-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211230_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('O+', 'O+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('B+', 'B+'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('O+', 'O+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('B+', 'B+'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C-', 'C-'), ('D', 'D'), ('B', 'B'), ('C', 'C'), ('B+', 'B+'), ('C+', 'C+'), ('F', 'F'), ('D+', 'D+'), ('A+', 'A+'), ('A-', 'A-'), ('B-', 'B-'), ('A', 'A')], max_length=2, null=True),
        ),
    ]
