# Generated by Django 3.2.9 on 2021-12-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211205_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('AB+', 'AB+'), ('A+', 'A+'), ('B+', 'B+'), ('O-', 'O-'), ('A-', 'A-'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('AB+', 'AB+'), ('A+', 'A+'), ('B+', 'B+'), ('O-', 'O-'), ('A-', 'A-'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C-', 'C-'), ('C', 'C'), ('D+', 'D+'), ('B+', 'B+'), ('F', 'F'), ('C+', 'C+'), ('B-', 'B-'), ('B', 'B'), ('A', 'A'), ('A+', 'A+'), ('D', 'D'), ('A-', 'A-')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='takes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
