# Generated by Django 3.2.9 on 2022-01-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220105_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='i',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='advisor',
            old_name='s',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('O-', 'O-'), ('AB-', 'AB-'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('O-', 'O-'), ('AB-', 'AB-'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('D+', 'D+'), ('D', 'D'), ('C+', 'C+'), ('C', 'C'), ('B-', 'B-'), ('C-', 'C-'), ('A', 'A'), ('F', 'F'), ('B', 'B'), ('B+', 'B+'), ('A-', 'A-'), ('A+', 'A+')], max_length=2, null=True),
        ),
    ]
