# Generated by Django 3.2.9 on 2021-11-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211129_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='sec_id',
            new_name='secId',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('secId', 'course', 'semester', 'year'), ('semester', 'year', 'time_slot', 'instructor'), ('semester', 'year', 'time_slot', 'course'), ('classroom', 'semester', 'year', 'time_slot'), ('course', 'secId', 'semester', 'year', 'time_slot')},
        ),
    ]
