# Generated by Django 3.2.9 on 2021-11-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211124_0013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'sec_id')},
        ),
    ]
