# Generated by Django 3.2.9 on 2021-11-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211130_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='time_slot',
            new_name='timeSlot',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('semester', 'year', 'timeSlot', 'course'), ('secId', 'course', 'semester', 'year'), ('semester', 'year', 'timeSlot', 'instructor'), ('course', 'secId', 'semester', 'year', 'timeSlot'), ('classroom', 'semester', 'year', 'timeSlot')},
        ),
    ]
