# Generated by Django 3.2.9 on 2021-12-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211222_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB-', 'AB-'), ('AB+', 'AB+'), ('A+', 'A+'), ('O-', 'O-'), ('B+', 'B+'), ('A-', 'A-'), ('O+', 'O+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB-', 'AB-'), ('AB+', 'AB+'), ('A+', 'A+'), ('O-', 'O-'), ('B+', 'B+'), ('A-', 'A-'), ('O+', 'O+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('C+', 'C+'), ('D', 'D'), ('A-', 'A-'), ('A+', 'A+'), ('D+', 'D+'), ('C-', 'C-'), ('C', 'C'), ('B+', 'B+'), ('A', 'A'), ('B', 'B'), ('B-', 'B-')], max_length=2, null=True),
        ),
    ]
