# Generated by Django 3.2.9 on 2021-11-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_section_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'sec_id', 'semester', 'year')},
        ),
    ]
