# Generated by Django 3.2.9 on 2021-12-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211205_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O-', 'O-'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O-', 'O-'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('A', 'A'), ('D', 'D'), ('D+', 'D+'), ('C', 'C'), ('F', 'F'), ('C-', 'C-'), ('A+', 'A+'), ('C+', 'C+'), ('A-', 'A-'), ('B-', 'B-'), ('B', 'B')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.section'),
        ),
    ]
