# Generated by Django 3.2.9 on 2021-12-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211230_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A+', 'A+'), ('O-', 'O-'), ('AB-', 'AB-'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A+', 'A+'), ('O-', 'O-'), ('AB-', 'AB-'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('B+', 'B+'), ('D', 'D'), ('A', 'A'), ('D+', 'D+'), ('B', 'B'), ('C+', 'C+'), ('A+', 'A+'), ('C-', 'C-'), ('C', 'C'), ('B-', 'B-'), ('A-', 'A-')], max_length=2, null=True),
        ),
    ]
