# Generated by Django 3.2.9 on 2021-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='studentId',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
