# Generated by Django 3.2.9 on 2021-12-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211222_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='completedCourses',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('A+', 'A+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('B+', 'B+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('A+', 'A+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('B+', 'B+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B-', 'B-'), ('C', 'C'), ('B+', 'B+'), ('F', 'F'), ('A-', 'A-'), ('D+', 'D+'), ('C-', 'C-'), ('B', 'B'), ('C+', 'C+'), ('D', 'D')], max_length=2, null=True),
        ),
    ]
