# Generated by Django 3.2.9 on 2021-12-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211230_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('B+', 'B+'), ('O-', 'O-'), ('AB+', 'AB+'), ('A-', 'A-'), ('A+', 'A+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('B+', 'B+'), ('O-', 'O-'), ('AB+', 'AB+'), ('A-', 'A-'), ('A+', 'A+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C-', 'C-'), ('B+', 'B+'), ('A', 'A'), ('D', 'D'), ('B-', 'B-'), ('D+', 'D+'), ('C+', 'C+'), ('F', 'F'), ('A-', 'A-'), ('A+', 'A+'), ('B', 'B'), ('C', 'C')], max_length=2, null=True),
        ),
    ]
