# Generated by Django 3.2.9 on 2021-11-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211130_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='takes',
            name='takes_id',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
