# Generated by Django 3.2.9 on 2021-11-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_section_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together={('takes_id', 'section')},
        ),
    ]
