# Generated by Django 3.2.9 on 2021-12-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211231_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('A+', 'A+'), ('O-', 'O-'), ('A-', 'A-'), ('B+', 'B+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('A+', 'A+'), ('O-', 'O-'), ('A-', 'A-'), ('B+', 'B+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('B+', 'B+'), ('A-', 'A-'), ('D', 'D'), ('F', 'F'), ('C+', 'C+'), ('B-', 'B-'), ('A+', 'A+'), ('C-', 'C-'), ('A', 'A'), ('D+', 'D+')], max_length=2, null=True),
        ),
    ]
