# Generated by Django 3.2.9 on 2021-11-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211124_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('course', models.OneToOneField(db_column='course', on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_course', to='accounts.section')),
                ('sec', models.OneToOneField(db_column='sec_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_sec', to='accounts.section')),
                ('semester', models.OneToOneField(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_semester', to='accounts.section')),
                ('takes_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('year', models.OneToOneField(db_column='year', on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_year', to='accounts.section')),
            ],
            options={
                'unique_together': {('id', 'course', 'semester', 'year'), ('id', 'course', 'sec', 'semester', 'year')},
            },
        ),
    ]
