# Generated by Django 3.2.9 on 2021-12-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211231_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('B+', 'B+'), ('A+', 'A+'), ('O+', 'O+'), ('AB+', 'AB+'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('B+', 'B+'), ('A+', 'A+'), ('O+', 'O+'), ('AB+', 'AB+'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('A', 'A'), ('C+', 'C+'), ('F', 'F'), ('D', 'D'), ('A+', 'A+'), ('D+', 'D+'), ('C-', 'C-'), ('C', 'C')], max_length=2, null=True),
        ),
    ]
