# Generated by Django 3.2.9 on 2021-11-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211124_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.section'),
        ),
    ]
