# Generated by Django 3.2.9 on 2021-12-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211231_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('AB-', 'AB-'), ('A+', 'A+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Spring', 'Spring'), ('Fall', 'Fall')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('AB-', 'AB-'), ('A+', 'A+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('F', 'F'), ('A+', 'A+'), ('B', 'B'), ('D+', 'D+'), ('A', 'A'), ('C-', 'C-'), ('D', 'D'), ('B-', 'B-'), ('C+', 'C+'), ('A-', 'A-'), ('C', 'C')], max_length=2, null=True),
        ),
    ]
