# Generated by Django 3.2.9 on 2021-12-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211231_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O-', 'O-'), ('A+', 'A+'), ('B+', 'B+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O-', 'O-'), ('A+', 'A+'), ('B+', 'B+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('C+', 'C+'), ('A', 'A'), ('B-', 'B-'), ('D', 'D'), ('C-', 'C-'), ('A+', 'A+'), ('D+', 'D+'), ('B+', 'B+'), ('F', 'F'), ('A-', 'A-')], max_length=2, null=True),
        ),
    ]
