# Generated by Django 3.2.9 on 2021-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211130_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='DefaultProfilePic.jpg', null=True, upload_to='pics'),
        ),
    ]
