# Generated by Django 3.2.9 on 2021-11-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211124_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('section', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.section')),
                ('takes_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
