# Generated by Django 3.2.9 on 2021-11-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_takes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('teaches_id', 'section')},
        ),
    ]
