# Generated by Django 3.2.9 on 2021-11-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211121_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('img', models.ImageField(blank=True, default=0, null=True, upload_to='pics')),
                ('studentId', models.CharField(max_length=13, unique=True)),
                ('admitted_semester', models.CharField(blank=True, max_length=30, null=True)),
                ('advisor', models.CharField(blank=True, max_length=30, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('O-', 'O-'), ('B+', 'B-'), ('A+', 'A+')], max_length=3, null=True)),
                ('present_address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('department', models.CharField(blank=True, choices=[('EEE', 'EEE'), ('CSE', 'CSE'), ('BBA', 'BBA'), ('ENG', 'ENG'), ('ICE', 'ICE')], max_length=5, null=True)),
            ],
        ),
    ]
