# Generated by Django 3.2.9 on 2021-11-21 16:44

from django.db import migrations, models
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20211121_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('AB-', 'AB-'), ('B+', 'B-'), ('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('O-', 'O-'), ('AB+', 'AB+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('EEE', 'EEE'), ('CSE', 'CSE'), ('ICE', 'ICE'), ('ENG', 'ENG'), ('BBA', 'BBA')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=mirage.fields.EncryptedCharField(max_length=255),
        ),
    ]
