# Generated by Django 3.2.9 on 2021-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20211130_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='static/images/DefaultProfilePic.jpg', null=True, upload_to='pics'),
        ),
    ]
