# Generated by Django 3.2.9 on 2021-11-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20211121_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admitted_semester',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('AB-', 'AB-'), ('O-', 'O-'), ('B+', 'B+'), ('A+', 'A+'), ('B+', 'B-'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ENG', 'ENG'), ('ICE', 'ICE'), ('BBA', 'BBA'), ('EEE', 'EEE')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
