# Generated by Django 3.2.9 on 2021-11-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_section_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(default='DefaultProfilePic.jpg', null=True, upload_to='pics'),
        ),
    ]
