# Generated by Django 3.2.9 on 2021-11-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20211121_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('A+', 'A+'), ('O-', 'O-'), ('AB-', 'AB-'), ('B+', 'B-'), ('AB+', 'AB+'), ('A-', 'A-'), ('O+', 'O+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('EEE', 'EEE'), ('CSE', 'CSE'), ('ENG', 'ENG'), ('ICE', 'ICE'), ('BBA', 'BBA')], max_length=5, null=True),
        ),
    ]
