# Generated by Django 3.2.9 on 2021-12-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20211202_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='instructor',
            name='lastName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
