# Generated by Django 3.2.9 on 2021-11-21 17:17

from django.db import migrations, models
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20211121_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='student',
            name='password2',
            field=mirage.fields.EncryptedCharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('A-', 'A-'), ('AB-', 'AB-'), ('A+', 'A+'), ('AB+', 'AB+'), ('O+', 'O+'), ('B+', 'B+'), ('B+', 'B-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('BBA', 'BBA'), ('EEE', 'EEE'), ('ICE', 'ICE'), ('ENG', 'ENG'), ('CSE', 'CSE')], max_length=5, null=True),
        ),
    ]
