# Generated by Django 3.2.9 on 2021-11-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20211121_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B+', 'B-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('ICE', 'ICE'), ('EEE', 'EEE'), ('ENG', 'ENG'), ('BBA', 'BBA'), ('CSE', 'CSE')], max_length=5, null=True),
        ),
    ]
