# Generated by Django 3.2.9 on 2021-11-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20211122_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('AB-', 'AB-'), ('B+', 'B-'), ('O+', 'O+'), ('A-', 'A-'), ('O-', 'O-'), ('AB+', 'AB+'), ('A+', 'A+'), ('B+', 'B+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('BBA', 'BBA'), ('EEE', 'EEE'), ('ENG', 'ENG'), ('ICE', 'ICE')], max_length=5, null=True),
        ),
    ]
