# Generated by Django 3.2.9 on 2021-11-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20211122_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admitted_semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='present_address',
        ),
    ]
