# Generated by Django 3.2.9 on 2021-11-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20211122_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='deptName',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='prereq',
            old_name='prereqId',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='deptName',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='takes',
            old_name='courseId',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='takes',
            old_name='takesId',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6, null=True),
        ),
    ]
