# Generated by Django 3.2.9 on 2021-11-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20211122_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('C-', 'C-'), ('D+', 'D+'), ('B-', 'B-'), ('D', 'D'), ('C', 'C'), ('B+', 'B+'), ('B', 'B'), ('A-', 'A-'), ('F', 'F'), ('C+', 'C+'), ('A+', 'A+'), ('A', 'A')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6, null=True),
        ),
    ]
