# Generated by Django 3.2.9 on 2021-11-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20211122_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='prereq',
            name='course',
        ),
        migrations.RemoveField(
            model_name='section',
            name='courseId',
        ),
        migrations.RemoveField(
            model_name='section',
            name='roomNumber',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Prereq',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Takes',
        ),
    ]
