# Generated by Django 3.2.9 on 2021-11-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20211122_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(blank=True, choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('B', 'B'), ('D+', 'D+'), ('C-', 'C-'), ('F', 'F'), ('B+', 'B+'), ('C+', 'C+'), ('A', 'A'), ('A+', 'A+'), ('A-', 'A-'), ('B-', 'B-'), ('C', 'C')], max_length=2, null=True),
        ),
    ]
